name: e_commerce_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  freezed_annotation:

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: